
on:
  release:
    types: [published]
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Restore workloads
      run:  dotnet workload restore
    - name: Add MedbaseLibrary Nuget Package
      run: dotnet add package MedbaseLibrary
    - name: Build
      run: dotnet build -c Release
      env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
